version: '3.8'

services:
  ai-news-reporter:
    build: .
    ports:
      - "1234:1234"   # Backend API
      - "8080:8080"   # Frontend UI
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY:-your_groq_api_key_here}
      - USE_BRIGHTDATA=${USE_BRIGHTDATA:-false}
      - WEB_UNLOCKER_ZONE=${WEB_UNLOCKER_ZONE:-}
      - BRIGHTDATA_API_KEY=${BRIGHTDATA_API_KEY:-}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY:-}
    volumes:
      - ./audio:/app/audio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1234/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    name: ai-news-reporter-network
